### ISSUE TITLE
Files are .mjs, but seem to be hand-written UMD

### ISSUE THREAD

**Issue by justinfagnani** [GoogleChromeLabs/dark-mode-toggle#1]
Is there a reason to do UMD style at all? A module defined a scope, so you don't need a function scope to keep from accidentally creating globals. If you did, you could just use a block `{}` anyway.

Also, both the source file and dist file have .mjs extensions even though neither has an import or export. Is there a reason to check-in the minified file? It can be published to npm and available via unpkg.com without being checked in.

**Comment by tomayac** [comment]
Thanks, @justinfagnani, let me address your comments.

>  Is there a reason to check-in the minified file? It can be published to npm and available via unpkg.com without being checked in.

I have fixed this. I wasn't aware of unpkg's super powers to deliver a file that isn't checked in. If you request https://unpkg.com/dark-mode-toggle, it now does the right thing. 🎉

> Also, both the source file and dist file have .mjs extensions even though neither has an import or export.

I took some inspiration from https://tkent-google.github.io/std-switch/src/switch.mjs (that exports something, but with a comment on not wanting to do that). Strictly speaking, as the registration happens on `window`, does it need to export something?

> Is there a reason to do UMD style at all? A module defined a scope, so you don't need a function scope to keep from accidentally creating globals. If you did, you could just use a block {} anyway.

I mostly use the IIFE pattern to help the minifier be more efficient.

**Comment by justinfagnani** [comment]
I'd like to know more about that comment in std-switch. We export every custom element class in all the Polymer Project libraries. I don't know of any hazard of doing that and it allows for subclassing and other things.

As for the IIFE, minifiers should understand modules now and know that their top-level declarations are scoped. babel-plugin-minify-mangle-names has the `topLevel` option which should work for this. At the very least you can use a block instead of an IIFE, but that shouldn't be necessary.

Also, the `.mjs` extension is completely unnecessary too. Even Node is going to support modules with the .js extension ;)

**Comment by tomayac** [comment]
Thanks, @justinfagnani, I have addressed the points you brought up (except for the `.mjs` bit after briefly consulting with @mathiasbynens).

> I'd like to know more about that comment in std-switch. We export every custom element class in all the Polymer Project libraries. I don't know of any hazard of doing that and it allows for subclassing and other things.

Not sure, but the author is @tkent-google. It doesn't seem to be a problem in general.

> As for the IIFE, minifiers should understand modules now and know that their top-level declarations are scoped. babel-plugin-minify-mangle-names has the topLevel option which should work for this. At the very least you can use a block instead of an IIFE, but that shouldn't be necessary.

I switched to terser-js, which doesn't have babel-plugin-minify-template-strings, but the top level minification there worked like a charm. I might eventually switch back to babel, still undecided.

**Comment by justinfagnani** [comment]
awesome!
