### ISSUE TITLE
Improve minification

### ISSUE THREAD

**Issue by tomayac** [GoogleChromeLabs/dark-mode-toggle#10]
The minification of template strings with [terser](https://github.com/terser/terser) currently is [suboptimal](https://unpkg.com/browse/dark-mode-toggle@0.4.5/dist/dark-mode-toggle.min.mjs), the problem being strings with repeated spaces and line breaks ending up in the minified code (excerpt):

```
`\n<style>\n*,\n::before,\n::after {\n  box-sizing: border-box;\n}\n\n:host {\n  […]`
```

This is most probably *me* [holding terser wrong](https://github.com/GoogleChromeLabs/dark-mode-toggle/blob/be335afdbf37201887ce7c5aec163cb0d9682a94/package.json#L19). Essentially I'm looking for something like [babel-plugin-minify-template-strings](https://www.npmjs.com/package/babel-plugin-minify-template-strings), but for terser. Help wanted.

CC: @RReverser @mathiasbynens

**Comment by mathiasbynens** [comment]
You don't just want minify-template-strings (i.e. just removing whitespace), you want minify-css-in-template-strings. I don't know of an existing tool that does this.

Some other ideas to reduce minified bundle size: #11

**Comment by mathiasbynens** [comment]
Is this necessary?

```css
:host([hidden]) {
  display: none;
}
```

I thought this was the default but am likely missing something.

**Comment by mathiasbynens** [comment]
Another thing that jumps out is `this.` occurs more than 150 times in the minified source. We could largely reduce that number by doing something like `const _this = this;` at the top of the `constructor`. `_this` can then be minified just like any other identifier.

Although this likely wouldn't reduce the gzip/brotli size, it would [reduce the number of bytes that need to be parsed and compiled](https://v8.dev/blog/scanner#conclusion).

**Comment by tomayac** [comment]
> Is [`:host([hidden]) {…}`] necessary?

Yes, it's a [best practice](https://developers.google.com/web/fundamentals/web-components/best-practices#add-a-:host-display-style-that-respects-the-hidden-attribute).

**Comment by tomayac** [comment]
> You don't just want minify-template-strings (i.e. just removing whitespace), you want minify-css-in-template-strings. I don't know of an existing tool that does this.

Eagerly awaiting [CSS modules](https://github.com/w3c/webcomponents/issues/759) that will make this so much better.

**Comment by mathiasbynens** [comment]
> > You don't just want minify-template-strings (i.e. just removing whitespace), you want minify-css-in-template-strings. I don't know of an existing tool that does this.
> 
> Eagerly awaiting [CSS modules](https://github.com/w3c/webcomponents/issues/759) that will make this so much better.

We could hack something together ourselves. The template literal's contents would be stored in a separate source file in the repository, and processed by a custom script that strips whitespace and applies some simple CSS optimizations. The result would then be injected as a template literal into the built `.js` file. The downside is that the source `*.js` file would no longer be useful for testing; you'd have to create a build just to get a working file. It's definitely a trade-off... Maybe it's worth it though.

Happy to prototype this if this doesn't sound too horrible to you.

**Comment by tomayac** [comment]
> We could hack something together ourselves.

Sure, but at this point you'd build a build system. I *really* preferred if we instead chimed in on making CSS Modules a thing rather sooner than later. If you could review their proposal and comment on it, this would be a better use of your brain in my opinion.

**Comment by tomayac** [comment]
> We could largely reduce that number by doing something like `const _this = this;` at the top of the constructor. `_this` can then be minified just like any other identifier.

Great idea, thanks. Could you add this to your PR? You can test the changes by running [`npm run start`](https://github.com/GoogleChromeLabs/dark-mode-toggle/blob/be335afdbf37201887ce7c5aec163cb0d9682a94/package.json#L14) and navigating to http://localhost:8080/demo (you have probably figured this out, but just thought I'd point it out). Will add this to the README as well.

**Comment by mathiasbynens** [comment]
> Great idea, thanks. Could you add this to your PR?

Tried it, but turns out not to save anything: https://github.com/GoogleChromeLabs/dark-mode-toggle/pull/11#issuecomment-538287526 So didn't add it to the PR.

Thanks for the pointer, I have been testing the changes!

**Comment by tomayac** [comment]
Also added the instructions [to the README](https://github.com/GoogleChromeLabs/dark-mode-toggle#hacking-on-dark-mode-toggle).

**Comment by tomayac** [comment]
Closed via https://github.com/GoogleChromeLabs/dark-mode-toggle/pull/11.  🎉
