### ISSUE TITLE
Play nice with DevTools overrides

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/dark-mode-toggle#17]
DevTools supports emulating `prefers-color-scheme`. It would be great if dark-mode-toggle could play nice with this functionality. Some discussion: https://github.com/v8/v8.dev/pull/254#discussion_r331992940 + the workaround @RReverser used to make this work for v8.dev: https://github.com/v8/v8.dev/pull/254/commits/8ab0b70e5e471f6c587783a85db84701c9ded448

**Comment by tomayac** [comment]
This has been addressed with https://github.com/GoogleChromeLabs/dark-mode-toggle/commit/ac488372df6a690c3c1a1a0386f76c497b708b4d, and the behavior now is now the one you forced through the (to be removed) work-around. Thanks for filing this issue.
