### ISSUE TITLE
dark-mode-toggle and SVG

### ISSUE THREAD

**Issue by jaygray0919** [GoogleChromeLabs/dark-mode-toggle#21]
we've experimented with your AMP variation. our planned site heavily uses SVG (rather than PNG/JPG). the dark-mode 'bleeds' thru the SVGs. we have a sample to share if you would like to see this use case. we would be willing to change our approach to using SVG linearGradient and radialGradient to work with dark-mode-toggle, but are uncertain how to do so. let me know if you are willing to collaborate with us on supporting SVGs and dark-mode-toggle.
/jay gray

**Comment by tomayac** [comment]
Hey @jaygray0919. I'd definitely be interested in seeing a sample. Thanks, Tom

**Comment by jaygray0919** [comment]
here's a simple example. you'll note that the CSS for the linearGradients is missing. i'm looking for a version with those CSS elements. but it does serve to highlight how the SVG is impacted by the switch. you also can see the problem by using this template: https://amp.dev/ where the SVGs are reversed on mouseover (we emulate the CSS used on the AMP home page).
we are willing to help here if you give us instructions about configuring different use-cases.

[_AMP-dark-mode_.zip](https://github.com/GoogleChromeLabs/dark-mode-toggle/files/3955473/_AMP-dark-mode_.zip)

**Comment by jaygray0919** [comment]
also, as you know, Chrome will not run the above attachment inline - it has to be on either a local or remote server. Firefox will run it inline for an easier preview.

**Comment by tomayac** [comment]
I'm sorry, but this has nothing to do with `<dark-mode-toggle>`, the custom element isn't even being used in your example. I suggest you open an [AMP issue](https://github.com/ampproject/amp.dev/issues/new?assignees=&labels=Status%3A+Pending+Triage%2C+Type%3A+Bug&template=bug.md&title=) regarding the SVG display problem.
