### ISSUE TITLE
Icon Flash on Mouse Hover

### ISSUE THREAD

**Issue by ghost** [GoogleChromeLabs/dark-mode-toggle#23]
When using custom PNGs for the light/dark, I'm seeing a brief flash of the icon when the mouse hovers over the icon and when moving off of the icon. Using the OOTB icons this doesn't happen.

```html
dark-mode-toggle {
  position: absolute;
  top: 0.5rem;
  right: 1rem;
  --dark-mode-toggle-light-icon: url(/assets/moon.png);
  --dark-mode-toggle-dark-icon: url(/assets/sun.png);
  --dark-mode-toggle-icon-size: 2rem;
  --dark-mode-toggle-icon-filter: invert(100%);
  transform:translate3d(0, 0, 0);
}
```

Not sure why this would be happening with custom PNGs.

**Comment by tomayac** [comment]
Could it be that this *only* happens with the Chrome DevTools open and the "Disable cache" checkbox checked? Can you try unchecking it as in the screenshot below?

![Screen Shot 2020-01-20 at 09 05 11](https://user-images.githubusercontent.com/145676/72708984-2c0c6680-3b64-11ea-85f7-a41be3bda867.png)

**Comment by tomayac** [comment]
I *think* this is a Chrome DevTools issue, as the Firefox DevTools don't show this behavior. I have opened https://crbug.com/1043588 to verify this hypothesis. 

In practice (that is, without Chrome DevTools open, you shouldn't see the flickering, so I hope this is not a problem in production.

**Comment by ghost** [comment]
No dev tools open, unfortunately. The behavior does not occur in Firefox, only Chrome and Edge Chromium.

**Comment by tomayac** [comment]
Interesting. Could you post a small reproduction case, please?

**Comment by ghost** [comment]
Well, perhaps you were right! I had been working on this in localhost via `jekyll serve` where it showed the behavior, even though I did not have the dev tools in the browser open. I just pushed the changes to https://thesharepointfarm.com/ and they seem to be OK!

Thank you for providing the additional info, though. That should be helpful for others :-)

**Comment by tomayac** [comment]
Thanks for letting me know. For your page, consider using SVGs instead of PNGs, they look a lot crisper, especially on high-resolution screens.
