### ISSUE TITLE
Flashes when system prefers dark, but light theme is toggled

### ISSUE THREAD

**Issue by francislavoie** [GoogleChromeLabs/dark-mode-toggle#25]
This even happens on the demo site. https://googlechromelabs.github.io/dark-mode-toggle/demo/index.html

Tested on both Chrome and Firefox.

System must be configured to prefer dark, then light theme must be toggled on and remembered in the site. On page change or refresh, sometimes you'll get a frame or two where the dark theme is rendered first, then it flips over to the light theme as expected. With the demo site, because there's a transition enabled, you get the dark theme fading back into the light theme.

Hopefully a workaround is found for this!

**Comment by tomayac** [comment]
Thanks for opening the issue. The problem you're describing was already discussed before, I have provided an answer in https://github.com/GoogleChromeLabs/dark-mode-toggle/issues/20#issuecomment-559265763. Hope this helps. I'm closing the issue, but feel free to comment again. Cheers!

**Comment by francislavoie** [comment]
Ah thanks, I searched for the wrong words 👍 

You said:

> So long story short, there’s no way to prevent this, but you can limit the negative effect by making sure the toggle code executes as soon as possible during the loading phase of your page. Hope this helps somewhat.

It seems to me like the toggle code doesn't run until `<dark-mode-toggle>` is encountered (I'm making this assumption because if the JS is in the `<head>` but the toggle element is not rendered, nothing happens). I put `<script type="module" src="https://unpkg.com/dark-mode-toggle"></script>` as early as possible in the `<head>` but it still happens. Is there anything else I could do to make it load earlier?

**Comment by tomayac** [comment]
You could [preload the module](https://developers.google.com/web/updates/2017/12/modulepreload#so_is_link_relmodulepreload_just_link_relpreload_for_modules):

```html
<link rel="modulepreload" src="https://unpkg.com/dark-mode-toggle" crossorigin>
```

**Comment by francislavoie** [comment]
Hmm, looks like that's still experimental https://caniuse.com/#feat=link-rel-modulepreload

**Comment by tomayac** [comment]
It is experimental. But where it works, it helps. And where it doesn't work, it doesn't cause harm.
