### ISSUE TITLE
Allow the use of Unicode emojis instead of images for icons

### ISSUE THREAD

**Issue by MrPropre** [GoogleChromeLabs/dark-mode-toggle#27]
@tomayac 
Hello! It would be cool if we could use Unicode emojis (☀🌙) instead of images for icons. Thank you in advance!

**Comment by tomayac** [comment]
You can do this today. Here's a [live example](https://attractive-funny-oviraptor.glitch.me/) (just the toggle, it doesn't implement dark mode).

```html
<dark-mode-toggle
      dark="🙈"
      light="🐵"
      style="--dark-mode-toggle-light-icon: none; --dark-mode-toggle-dark-icon: none;"
></dark-mode-toggle>
```
