### ISSUE TITLE
Transition question

### ISSUE THREAD

**Issue by wdphoto** [GoogleChromeLabs/dark-mode-toggle#28]
First off, this is dope.  Thank you.

I have a question about smooth transitions. I'm not a very experienced front-end developer, I'm a photographer trying to build my own stuff to avoid hosting fees while times are tough, and using the spare time to learn some html/css/js. 

I stumbled across this on web.dev when trying how to get a theme for a static site generator to default the OS light/dark but remember overwritten user controls.

In that article, you have..
`body {
  --duration: 0.5s;
   --timing: ease;

  color: var(--color);
  background-color: var(--background-color);

  transition:
    color var(--duration) var(--timing),
    background-color var(--duration) var(--timing);
}`
But there is no mention of it in the github version.  With it still applied, the page blips from light to dark when the mode is permanent. I was curious what I need to look at specifically to fix that.

**Comment by wdphoto** [comment]
I guess I should have looked at the closed Issues. 

It appears there's no possible known fix for that. Bummer.

**Comment by tomayac** [comment]
If this is purely about the smooth transition, you can see a demo of that in action here: https://dark-mode-baseline.glitch.me/. Hope this helps!

**Comment by wdphoto** [comment]
Thanks.  Originally I was trying to load the OS default too, and have a toggle switch, but it would blip if you toggled the option on the site and then navigated to a new page/url on the site.  

I came to the conclusion that it wasn't a simple fix, if possible at all, and I'd either need to default to the OS or just have a toggle switch option.

**Comment by jakiisheep** [comment]
Sorry for the necropost, but sharing if anyone comes across this problem in the future.
After reading this issue I was out of hope because it also wasn't working for me. 
I tried a second time adding the `transition: 0.5s ease;` to both the light.css and dark.css and it just started working all of a sudden. It also worked with the `permanent` property.

**Comment by tomayac** [comment]
> I tried a second time adding the `transition: 0.5s ease;` to both the light.css and dark.css and it just started working all of a sudden.

It's definitely possible to make this work with just one declaration in the shared stylesheet. See https://dark-mode-baseline.glitch.me/style.css (and compare https://dark-mode-baseline.glitch.me/dark.css and https://dark-mode-baseline.glitch.me/light.css).
