### ISSUE TITLE
Extra margin

### ISSUE THREAD

**Issue by rctneil** [GoogleChromeLabs/dark-mode-toggle#29]
I have my toggle set up as a toggle and the permanent attribute set.  The icon I am using has a 1x1 aspect but I get some random margin on the right and bottom so the width doesn't match the height?

How can I remove these margins?

Also a way to be able to remove or alter the style of the focus styles would be useful.

**Comment by tomayac** [comment]
I have just published version 0.7.0 that allows you to use [`::part()`](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) styling. You can use this as I have done [in the demo](https://github.com/GoogleChromeLabs/dark-mode-toggle/blob/5d8b192752ff21e2daeefecd433ff2fc89eeff7f/demo/common.css#L125-L127).
