### ISSUE TITLE
Make shadow root accessible from JavaScript

### ISSUE THREAD

**Issue by njordhov** [GoogleChromeLabs/dark-mode-toggle#32]
Consider setting the `attachShadow` mode to `open` instead of `closed` so the internal dark-mode-toggle elements are accessible from outside the root, benefiting hacking into the functionality:

https://github.com/GoogleChromeLabs/dark-mode-toggle/blob/403ded79dc744fd7d3ac32a4b74c598e6ce1c148/src/dark-mode-toggle.mjs#L113

**Comment by tomayac** [comment]
(Sorry for the delay, I was OoO.)

This is a very reasonable suggestion, I will draft a release in the next few days and update this issue once it’s live.

**Comment by tomayac** [comment]
Fixed with https://github.com/GoogleChromeLabs/dark-mode-toggle/commit/090b967e858191d4433c733f893efb8cec0694de.
