### ISSUE TITLE
Failed to load module script: The server responded 

### ISSUE THREAD

**Issue by EgoistDeveloper** [GoogleChromeLabs/dark-mode-toggle#34]
hi i wanted to download the source code and run it on localhost but unfortunately i get this error every time. what's the problem ? how can i solve?

no changes have been made to the file I get this error even when I want to use the demos

Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by tomayac** [comment]
It looks like your local server is not set up correctly to serve `.mjs` files with the `text/javascript` MIME type. This is a [fixed requirement](https://v8.dev/features/modules#mjs:~:text=as%20long%20as%20the%20file%20is%20served%20with%20the%20JavaScript%20MIME%20type%20text%2Fjavascript). Instructions on how to enable this vary by server (here's one way to do it [for Apache](https://stackoverflow.com/questions/55995339/es6-import-using-mjs-suffix-fails-with-mime-error)). Hope this helps!
