### ISSUE TITLE
dark mode switch error

### ISSUE THREAD

**Issue by EgoistDeveloper** [GoogleChromeLabs/dark-mode-toggle#35]
When dark mode is active, when I refresh the page, it loads "LIGHT" first and then goes into dark mode. how can i fix this. If dark is selected, install dark.
it seems a little silly to start "light" first and switch to darkness immediately. I wonder if there is an error in my codes. I'm waiting for your help
you understand what I want to say from the video.
 [video](https://youtu.be/coKim0WlloM)

    
    <meta name="color-scheme" content="dark light"/>
    <meta name="theme-color" content="rgb(174, 129, 7)"/>
    <link rel="icon" content="">
    <link rel="stylesheet" href="'dark-mode/styles/light.css'" media="(prefers-color-scheme: light)">
    <link rel="stylesheet" href="'dark-mode/styles/dark.css'" media="(prefers-color-scheme: dark)">
    <link rel="stylesheet" href="'dark-mode/styles/common.css'">
    <script type="module" src="'dark-mode/scripts/dark-mode-toggle.mjs'"></script>
    <script type="module" src="'dark-mode/scripts/dark-mode-toggle-playground.mjs'"></script>
    script
        if (window.matchMedia('(prefers-color-scheme)').media === 'not all') {
            document.documentElement.style.display = 'none';
            document.head.insertAdjacentHTML(
                'beforeend',
                '<link rel="stylesheet" href="dark-mode/styles/light.css" onload="document.documentElement.style.display = ``">'
            );
        }
    </script>
    <aside><dark-mode-toggle id="dark-mode-toggle-2" permanent></dark-mode-toggle></aside>

**Comment by tomayac** [comment]
This has been discussed in https://github.com/GoogleChromeLabs/dark-mode-toggle/issues/20#issuecomment-559265763. Unfortunately there is nothing you can do, you setup looks great. In general just make sure that the toggle code runs as soon as possible, since it's responsible for switching the stylesheets.
