### ISSUE TITLE
customElements is not defined

### ISSUE THREAD

**Issue by MrPropre** [GoogleChromeLabs/dark-mode-toggle#36]
Hello @tomayac,

In old browsers like Firefox 52, there is no support for Custom Elements. I'm using Webpack with Babel and I can't find a plugin to support Custom Elements. So i suggest you to do nothing if customElements is not defined.

```js
// Do nothing if `customElements` does not exist. 
if (!window.customElements) return;
```

Thank you in advance !

**Comment by tomayac** [comment]
Please check out https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs. You can include the polyfills before loading the custom element.
