### ISSUE TITLE
CSS custom property to change the icon size

### ISSUE THREAD

**Issue by arnellebalane** [GoogleChromeLabs/dark-mode-toggle#4]
Hey @tomayac , thank you for this custom element! I've started using it on a remake on my site and I really like it, it's been fun and easy to use! 🎉 

I'm just wondering if there's a way to change the size of the icons? I see that there are CSS custom properties to change the font size of the labels, but I couldn't find one for the icons (please correct me if I'm wrong, I might have just missed it 😅 ).

I see from [dark-mode-toggle.js#L127-130](https://github.com/GoogleChromeLabs/dark-mode-toggle/blob/master/src/dark-mode-toggle.mjs#L127-L130) that the icons have a size of `1rem`, maybe a `--dark-mode-toggle-icon-size` custom property to customize this value?

Thanks! 😄

**Comment by tomayac** [comment]
Thanks for the issue, the `--dark-mode-toggle-icon-size` is now configurable! 🎉

![Screen Shot 2019-07-31 at 13 22 50](https://user-images.githubusercontent.com/145676/62208200-6f94cd80-b396-11e9-8f18-0055f6e3a0c3.png)

**Comment by arnellebalane** [comment]
Thank you @tomayac ! 💯🎉
