### ISSUE TITLE
Extra unnecessary right margin

### ISSUE THREAD

**Issue by aress31** [GoogleChromeLabs/dark-mode-toggle#40]
When not setting a legend on the component there is still a right margin relative to the icon, see the following screenshot:

![image](https://user-images.githubusercontent.com/11601622/92328774-fe285380-f05a-11ea-80cb-ace38dbcfde6.png)

When no legends are set should not the icon be centred with no extra unnecessary margin?

EDIT: Also, why is the `fieldset` so wide compared to the icon, could we make the `fieldset` the same area than the icon or add a CSS vars to customise the `fieldset`? My goal here would be to set the `width` and `height` of the `fieldset` to `32px` to match the other icons contained within `mwc-button-icon`.

![image](https://user-images.githubusercontent.com/11601622/92329031-b6a2c700-f05c-11ea-8ce3-75ac531d9248.png)

**Comment by tomayac** [comment]
I have just [fixed](https://github.com/GoogleChromeLabs/dark-mode-toggle/commit/a6692d5f62a3568489a3c9d0e06aa138586cc1ce) this with the freshly released v0.7.3.

**Comment by aress31** [comment]
@tomayac thanks for the quick fix, how can I set the size of the `fieldset` to `32x32px`?

**Comment by tomayac** [comment]
Please first familiarize yourself with [`::part`](https://developer.mozilla.org/en-US/docs/Web/CSS/::part). Then check the exposed [parts](https://github.com/GoogleChromeLabs/dark-mode-toggle#style-customization).

**Comment by aress31** [comment]
Yes just needed to do:
```
      dark-mode-toggle::part(fieldset) {
        padding: 6px;
      }
```
