### ISSUE TITLE
[Feature Request] Set SVG icons

### ISSUE THREAD

**Issue by aress31** [GoogleChromeLabs/dark-mode-toggle#41]
Could it be possible to add the option to set SVG icons for light and dark icon toogle?

**Comment by tomayac** [comment]
You can absolutely do this, just set the `--dark-mode-toggle-light-icon` and `--dark-mode-toggle-dark-icon` variables (you might want to combine this with `--dark-mode-toggle-icon-filter`, so you can invert one of the icons). Check, for example, my [blog's source code](https://github.com/tomayac/blogccasion/blob/master/css/main.css#L362-L363) where I do this. See the [documentation](https://github.com/GoogleChromeLabs/dark-mode-toggle#style-customization) for details.
