### ISSUE TITLE
Unable to Load png files when running on Github Pages

### ISSUE THREAD

**Issue by PrudhviVajja** [GoogleChromeLabs/dark-mode-toggle#43]
It is somewhat weird that the png files are loading when I ran locally but were unable to load properly after committing the code to Github and ran using Github pages. (I am able to use the button but it is transparent🤷‍♂️.) 
I am unable to figure out what is happening?

[Link to Source Code](https://github.com/PrudhviVajja/PrudhviVajja.github.io/tree/darkmode)

**Local** *The moon png in the navigation bar*
![image](https://user-images.githubusercontent.com/34853447/98350401-46c3a500-1fe9-11eb-8df6-dc82ae051505.png)

**Github Pages**
![image](https://user-images.githubusercontent.com/34853447/98350466-63f87380-1fe9-11eb-9eba-e0da0108de5b.png)

Code Snippets:
**CSS**
![image](https://user-images.githubusercontent.com/34853447/98350898-f6007c00-1fe9-11eb-95c8-6c9fce4492ea.png)

**HTML**
![image](https://user-images.githubusercontent.com/34853447/98350964-0ca6d300-1fea-11eb-970b-c60b94968f81.png)

**HEAD**
![image](https://user-images.githubusercontent.com/34853447/98351432-abcbca80-1fea-11eb-91d0-1b222ed88d07.png)

**Comment by tomayac** [comment]
This is a peculiarity of GitHub pages: locally, paths like `/assets` work, but on GitHub pages you have a URL like `username.github.io/reponame/`, so `/assets` no longer resolves correctly. Use relative paths instead. See this [StackOverflow discussion](https://stackoverflow.com/questions/16316311/github-pages-and-relative-paths), where they have a similar problem.

**Comment by PrudhviVajja** [comment]
Thanks, @tomayac
