### ISSUE TITLE
Add aria-label for lighthouse

### ISSUE THREAD

**Issue by aress31** [GoogleChromeLabs/dark-mode-toggle#47]
When running the Chrome lighthouse, I am getting the following accessibility issue:

![image](https://user-images.githubusercontent.com/11601622/114312421-918e9f00-9aea-11eb-9e86-42cf00f0b5dd.png)

![image](https://user-images.githubusercontent.com/11601622/114312448-9eab8e00-9aea-11eb-99c0-397f65149cc7.png)

Could you please easer hard code an aria-label value or pass it down as a property?

**Comment by tomayac** [comment]
I think this is a different `input#t` (the toggle's IDs can re-appear on the page due to the toggle using shadow DOM), since as you can see from your screenshot the input from the toggle does have an associated label.

I also ran Lighthouse on other pages that include the toggle, and everything was fine. I can't see the URL of the page you tested with, but try checking if the page uses `input#t` somewhere.

**Comment by Sungodragon** [comment]
This issue is present on https://googlechromelabs.github.io/dark-mode-toggle/demo/index.html

Kindly check from Chrome Lighthouse

![image](https://user-images.githubusercontent.com/16954963/133264490-cb0aa474-c967-4bc4-8096-2dc77f060391.png)

**Comment by tomayac** [comment]
I'm sorry, I see the problem now. While the `label` is always there, some toggle styles means they are empty, requiring an ARIA label. I completely missed this, apologies again. Re-opening the Issue, and hoping to release a fix later this week.

**Comment by Sungodragon** [comment]
I have Fixed the issue with aria-label="Toggle Theme" by adding it here, FYI I am a Junior Dev so I was just fiddling with these things. I have used the Source un minified HTML here.

![image](https://user-images.githubusercontent.com/16954963/133275768-72bc5059-ac42-46fc-9f15-92aae66bd2c9.png)

**Comment by tomayac** [comment]
Thanks both, @Sungodragon and @aress31! This has now been fixed for good via https://github.com/GoogleChromeLabs/dark-mode-toggle/commit/c5a79ae540e608ec2e3313d8ee225986de215702. I have just released `v0.9.0` that includes this fix.
