### ISSUE TITLE
Class based

### ISSUE THREAD

**Issue by rctneil** [GoogleChromeLabs/dark-mode-toggle#5]
I built practically the same system for a site i'm working on but I actually really like some of the ideas you have put in here.  My issue is that my dark/light styling is controlled via a high-level class.  Could this be tweaked to allow a top-level class to be used rather than multiple stylesheets?

Thanks

**Comment by tomayac** [comment]
Hi Neil,

You can actually easily support this single-file, class-controlled approach with `<dark-mode-toggle>`, here’s a Glitch demo that shows you how: https://glitch.com/~dark-mode-class-toggle. I leave this Issue open to document this in the README, but I hope with the sample code you’re unlocked now already.

**Comment by tomayac** [comment]
Documented in https://github.com/GoogleChromeLabs/dark-mode-toggle/commit/a24a394d8d9ccb26aaa5f2d7d2d3c19c35f9e442.
