### ISSUE TITLE
Dead GitHub Pages

### ISSUE THREAD

**Issue by MarioPerini** [GoogleChromeLabs/dark-mode-toggle#51]
The GitHub Page is dead: https://googlechromelabs.github.io/dark-mode-toggle/

**Comment by tomayac** [comment]
Thank you. I have renamed the `master` branch to `main`, which means GitHub pages need to be retriggered to build. This has happened now, and the [demo](https://googlechromelabs.github.io/dark-mode-toggle/demo/index.html) is live again.
