### ISSUE TITLE
Can't get to work

### ISSUE THREAD

**Issue by rctneil** [GoogleChromeLabs/dark-mode-toggle#6]
Hey,

I've pretty much copied the examples and put the dark-mode-toggle markup into my code but I see absolutely no output. The element has no width or height or anything.   Any ideas where I may be going wrong?

**Comment by tomayac** [comment]
Did you set the icons via the [CSS variables](https://github.com/GoogleChromeLabs/dark-mode-toggle/blob/master/README.md#style-customization)? Or else, if this doesn’t help, can you share your code somehow?

**Comment by rctneil** [comment]
I've not changed any CSS vars.  I literally have this in the `<head>`:

```
    <script>
      import * as DarkModeToggle from 'https://cdn.pika.dev/dark-mode-toggle';

      const toggle = document.querySelector('dark-mode-toggle');
      const body = document.body;

      toggle.mode = matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
      body.className = toggle.mode;

      toggle.addEventListener('colorschemechange', () => {
        body.className = toggle.mode;
      });
    </script>
```

and this further down in my view:

`<dark-mode-toggle dark="dark" light="light" appearance="switch" remember="Remember this"></dark-mode-toggle>`

**Comment by tomayac** [comment]
You need to give your script a type:

`<script type="module">`

**Comment by rctneil** [comment]
Ah perfect.  Before i had it in a script tag i had it in my main js file which is where i'd prefer it to be and it also failed there.  How would I get that to work?

**Comment by tomayac** [comment]
Happy this works now. For modules documentation, please check [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules).
