### ISSUE TITLE
Dark mode website

### ISSUE THREAD

**Issue by Agansulisfiana** [GoogleChromeLabs/dark-mode-toggle#65]

**Comment by tomayac** [comment]
What’s the problem?

**Comment by Erik-Egnatosyan** [comment]
The text next to the theme change is not displayed.

**Comment by tomayac** [comment]
I'm investigating, thank you!

**Comment by tomayac** [comment]
Just released version `0.12.0` that fixes this issue. Sorry for the interruption.

**Comment by tomayac** [comment]
Actually, version `0.13.0` is even better.
