### ISSUE TITLE
"Permanent" property seems to have stopped working

### ISSUE THREAD

**Issue by TheDonCaprio** [GoogleChromeLabs/dark-mode-toggle#66]
I've been using this on all my websites for about a year now, and I appreciate that it's been working great. However, I just found out that the "permanent" toggle seems to have stopped working even though it's set to true. It keeps reverting to the default system theme.

I'm using via this CDN: https://googlechromelabs.github.io/dark-mode-toggle/src/dark-mode-toggle.mjs

I've tried on different browsers just to be sure it's not a browser issue.

**Comment by tomayac** [comment]
Can you tell me the URL of a site where it isn't working?

**Comment by TheDonCaprio** [comment]
> 

https://nerdiedad.com/

**Comment by Erik-Egnatosyan** [comment]
In my website doesn't work too. And text next to the theme change is not displayed.

**Comment by tomayac** [comment]
Just released version `0.12.0` that fixes this issue. Sorry for the interruption.

**Comment by tomayac** [comment]
Actually, version `0.13.0` is even better.
