### ISSUE TITLE
Implement saving light/dark mode

### ISSUE THREAD

**Issue by Deimos715** [GoogleChromeLabs/dark-mode-toggle#67]
Hello, could you tell me how can I implement saving light/dark mode on my site like here (https://v8.dev/) without "Remember" checkbox? Adding "permanent" parameter doesn't help. Though this parameter is set in this website code and theme is saved without the checkbox.

**Comment by tomayac** [comment]
The implementation on v8.dev is as follows:

```html
<dark-mode-toggle dark="Light Theme" light="Dark Theme" permanent></dark-mode-toggle>
```

You can debug if it works by checking in DevTools:

![Screenshot 2022-10-13 at 09 54 59](https://user-images.githubusercontent.com/145676/195536385-07733854-2a27-4e05-ac87-46c438b61bef.png)

**Comment by Deimos715** [comment]
Before I used the option "Remember" on my site which was implemented as checkbox. I removed it and set "permanent" parameter like on your site.
![Снимок экрана от 2022-10-13 19-29-29](https://user-images.githubusercontent.com/32176134/195657699-2a07e370-fc64-485b-9a6b-e716749a4e6f.png)

It shows in DevTools:
Light
![Снимок экрана от 2022-10-13 19-31-14](https://user-images.githubusercontent.com/32176134/195657788-3b593b64-06a1-4cef-bf4e-e88222b3b563.png)

Dark
![Снимок экрана от 2022-10-13 19-33-50](https://user-images.githubusercontent.com/32176134/195657826-1cbda8fa-8127-4e79-a9fc-b17f4030985f.png)

But theme is not saved when going on links. Could you tell me where may be a problem?

**Comment by tomayac** [comment]
Do you have a link to the site?

**Comment by Deimos715** [comment]
Yes, of course, https://wikilinux.ru.

**Comment by tomayac** [comment]
I think the problem is in your code, specifically the line

```js
toggleTheme({detail: {colorScheme: darkModeToggle.mode}});
```

See below the comment `// Remove this line ⤵️` in your JS:

```js
(() => {
  if (window.matchMedia('(prefers-color-scheme)').media === 'not all') {
    // alert('Your browser does not support the `prefers-color-scheme` media query.');
  }
  
  const darkModeToggle = document.querySelector('dark-mode-toggle');
  const manifests = document.querySelectorAll('link[rel="manifest"]');
  const favicons = document.querySelectorAll('link[rel="icon"]');
  const themeColor = document.querySelector('meta[name="theme-color"]');
      
  const toggleTheme = (e) => {    
    const darkModeOn = e.detail.colorScheme === 'dark' ? true : false;        
    manifests.forEach((link) => {               
      link.href = darkModeOn ? link.dataset.hrefDark : link.dataset.hrefLight; 
    });
    favicons.forEach((link) => {      
      link.href = darkModeOn ? link.dataset.hrefDark : link.dataset.hrefLight;   
    });    
    themeColor.content = darkModeOn ? 'black' : 'white';    
  };
  document.addEventListener('colorschemechange', toggleTheme);
  // Remove this line ⤵️
  toggleTheme({detail: {colorScheme: darkModeToggle.mode}});
})();

```

**Comment by tomayac** [comment]
You should also remove… 

```js
if (window.matchMedia('(prefers-color-scheme)').media === 'not all') {
    // alert('Your browser does not support the `prefers-color-scheme` media query.');
  }
```

…since it doesn't do anything… :-)

**Comment by Deimos715** [comment]
Unfortunately, it doesn't help

**Comment by tomayac** [comment]
I checked again, and it seems to work now. Perfect!
