### ISSUE TITLE
Dark mode doesn't work

### ISSUE THREAD

**Issue by Erik-Egnatosyan** [GoogleChromeLabs/dark-mode-toggle#68]
The buttons for changing from light to dark themes have disappeared on the site.

**Comment by Erik-Egnatosyan** [comment]
![image](https://user-images.githubusercontent.com/69196326/198596697-bafbe62f-ed49-4245-9d0b-f97a8872be87.png)

**Comment by tomayac** [comment]
Sorry, from what site? Our [demo](https://googlechromelabs.github.io/dark-mode-toggle/demo/index.html) still works. Probably your icons are hosted somewhere else.

**Comment by Erik-Egnatosyan** [comment]
On my website: [codenyx](https://www.codenyx.xyz/); there are no buttons and the library itself. Pls check your [link](https://unpkg.com/dark-mode-toggle).

**Comment by Erik-Egnatosyan** [comment]
![image](https://user-images.githubusercontent.com/69196326/198602625-95a58d5d-7d19-4f40-9c0e-b2a010f4d426.png)

**Comment by tomayac** [comment]
This is the unpkg CDN, it has nothing to do with Google, it’s an external service. I recommend hosting the code and the assets on infrastructure that you control.
