### ISSUE TITLE
Remember

### ISSUE THREAD

**Issue by rctneil** [GoogleChromeLabs/dark-mode-toggle#7]
Hey,

I find that the remember feature doesn't seem to work for me. I load the site with my OS appearance set to light, the site shows in light, I then toggle to dark which the dark-mode-toggle and click remember. I see the local storage key getting set. I refresh the page and it shows in light, the local storage key also switched the light. Any ideas?

Also, once the above is working, what does it do if you switch the OS mode to be equal to the permanent setting, does this remove the local storage key as they will match and are no longer required? This would be a cool feature to have.

**Comment by rctneil** [comment]
Any ideas? I just can't seem to get the remember feature to work?

**Comment by tomayac** [comment]
Hmm, it’s working fine here. I reproduced your flow, but the results were as expected. Can you maybe record a video that shows your experience (ideally with DevTools open)? Also: what browser is this on, and could you try without any extensions?

**Comment by rctneil** [comment]
@tomayac I'm using very latest Chrome. Here's a video showing the issue.

https://youtu.be/XI1pQNXSzoU

**Comment by rctneil** [comment]
@tomayac Oh and it does the same with no extensions running too.

**Comment by tomayac** [comment]
Can you let me know the browser version and what operating system? Also, can you share the relevant bits of code, please? This looks really strange.

**Comment by rctneil** [comment]
Chrome version: 76.0.3809.100

    <script type="module">
      import * as DarkModeToggle from 'https://cdn.pika.dev/dark-mode-toggle';

      const toggle = document.querySelector('dark-mode-toggle');
      const body = document.body;

      toggle.mode = matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
      body.classList.add(toggle.mode);
      document.documentElement.style.setProperty('--appearance', toggle.mode);
      document.documentElement.setAttribute('data-user-appearance', toggle.mode);

      toggle.addEventListener('colorschemechange', () => {
        body.classList.add(toggle.mode);
        document.documentElement.style.setProperty('--appearance', toggle.mode);
        document.documentElement.setAttribute('data-user-appearance', toggle.mode);
      });
    </script>

and

`<dark-mode-toggle dark="dark" light="light" appearance="switch" remember="Remember this" permanent></dark-mode-toggle>`

**Comment by tomayac** [comment]
OK, now I see it: in the line `body.classList.add(toggle.mode);` you add the new class according to the mode, but you never remove the old one. You need to either switch to `classList.toggle` as I do in https://glitch.com/edit/#!/dark-mode-class-toggle?path=script.js:14:56 when you work with just one class, or use `classList.remove` when you work with a "light" and a "dark" class.
