### ISSUE TITLE
Keep light mode after changing page for Wordpress Theme

### ISSUE THREAD

**Issue by maisondasilva** [GoogleChromeLabs/dark-mode-toggle#72]
I noticed that if the person is in light mode and switches to dark mode and refreshes the page it continues in dark mode, now if the person is in dark mode and switches to light and refreshes the page it does not work page back for dark.

I use a select button

![image](https://user-images.githubusercontent.com/11423362/215601559-d587c0bc-b83d-46fc-870d-6b11fd79f05f.png)

Can you help me?

```
// Get current theme
var theme = localStorage.getItem( 'theme' );
// Set defaults if theme is not defined.
if ( ! theme ) {
  localStorage.setItem( 'theme', 'light' );
  theme = 'light';
}
// Add theme to the body.
document.body.classList.add( theme );

// Handle onClick events
document.getElementById( 'theme-toggle' ).addEventListener( 'click', () => {
  // Cleanup classes from body.
  document.body.classList.remove( 'light' );
  document.body.classList.remove( 'dark' );
  // Change the theme.
  theme = ( theme === 'light' ) ? 'dark' : 'light';
  // Save the theme.
  localStorage.setItem( 'theme', theme );
  // Apply the theme.
  document.body.classList.add( theme );
});

if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
	document.body.classList.remove( 'light' );
	document.body.classList.remove( 'dark' );
    var theme = 'dark';
	localStorage.setItem( 'theme', theme );
	document.body.classList.add( theme );
}
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => {
	document.body.classList.remove( 'light' );
	document.body.classList.remove( 'dark' );
    var newColorScheme = event.matches ? "dark" : "light";
	localStorage.setItem( 'theme', newColorScheme );
	document.body.classList.add( newColorScheme );
});
```

**Comment by tomayac** [comment]
The toggle on your site https://www.maisondasilva.com.br/ is not using the custom element in this repo, `<dark-mode-toggle>`. I cannot provide support for non-related code. Most likely the problem is the line `if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {`, where you overwrite your stored variable based on the system settings.

**Comment by maisondasilva** [comment]
@tomayac  Thanks for the tip! If you want, you can delete my post, as it has nothing to do with your project. Thanks

**Comment by tomayac** [comment]
No worries. The Issue is closed and hopefully you have a pointer to debug your code, so all good.
