### ISSUE TITLE
Accessibility error

### ISSUE THREAD

**Issue by Sungodragon** [GoogleChromeLabs/dark-mode-toggle#73]
Tool used AXE https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd

Steps to reproduce
1) Install AXE devtools extension in Chrome
2) Go to https://v8.dev/
3) Inside inspect Run Scan Page
    No errors Found
4) Now change toggle Dark/Light Theme Once
5) Rerun The Scan
6) Error " Form Elements Must Have Label"

Element Location:
dark-mode-toggle,#p
<input part="permanentCheckbox" id="p" type="checkbox">
To solve this problem, you need to fix the following:
Form element has explicit <label> that is hidden

![image](https://github.com/GoogleChromeLabs/dark-mode-toggle/assets/16954963/3092fa1f-5ee7-4d39-b431-24cb60183c03)

**Comment by Sungodragon** [comment]
Probably implementing https://github.com/GoogleChromeLabs/dark-mode-toggle/issues/74 might fix this too.

**Comment by tomayac** [comment]
Thanks for the report. If you check the [accessibility tree](https://developer.chrome.com/blog/full-accessibility-tree/), though, you will notice that everything is labeled correctly:

![Screenshot 2023-06-12 at 09 51 54](https://github.com/GoogleChromeLabs/dark-mode-toggle/assets/145676/7cc61657-77b6-4e89-bc0e-319b05b72f04)
