### ISSUE TITLE
Consider aria-label="auto" aria-live="polite"

### ISSUE THREAD

**Issue by Sungodragon** [GoogleChromeLabs/dark-mode-toggle#74]
I am a junior Dev and While implementing dark-mode-toggle and my other study from the below Google article I came across
aria-label="auto" aria-live="polite" for theme component.

https://web.dev/building-a-theme-switch-component/

In this, we keep the aria-label auto by default and change it to "light" or "dark" based on our toggle switch.
Also aria-live="polite" seems to add up.

If possible kindly have a look at these enhancements if deemed appropriate.

**Comment by tomayac** [comment]
Closing as per https://github.com/GoogleChromeLabs/dark-mode-toggle/issues/73#issuecomment-1586779612.
