### ISSUE TITLE
Problems styling ::parts and pseudo elements such as ::before

### ISSUE THREAD

**Issue by tomasts248** [GoogleChromeLabs/dark-mode-toggle#78]
Hi, well its been interesting to learn about Shadow CSS and ::parts but how can I style :: before and ::after using parts? It seems is not possible to target both at the same time. In my case I need to set different values for icons in the select button/form for width and height so it seems current variables are not enough. Maybe the code related to the toggle/switch could be further simplified.

**Comment by tomayac** [comment]
According to the [spec](https://drafts.csswg.org/css-shadow-parts/#part:~:text=The%20%3A%3Apart()%20pseudo%2Delement%20can%20also%20take%20additional%20pseudo%2Delements%20after%20it%2C%20such%20as%20x%2Dbutton%3A%3Apart(label)%3A%3Abefore%2C%20but%20never%20match%20additional%20%3A%3Apart()s.), this should work using the following syntax:

```css
x-button::part(label)::before { … }
```

**Comment by tomasts248** [comment]
Thank you!!

**Comment by tomasts248** [comment]
Well I'm afraid is not working, all the rules with before and part pseudo classes are ignored with Cloudflare.
Is it really worth all the complexity and trouble of ::parts, is there any way to not use Shadow CSS?

**Comment by tomayac** [comment]
Hmm, would you have an example for me to look at?

**Comment by tomasts248** [comment]
Sure, please take a look at the right bottom for the button to toggle dark/light mode.
1. with Cloudflare cache enabled (rules not in effect)
https://www.tomastestart.com/
2. without (rules in effect)
https://www.tomastestart.com/?swcfpc=1

in the first case it looks this way:
![image](https://github.com/GoogleChromeLabs/dark-mode-toggle/assets/32283036/86ef705d-9aed-45e6-97b8-db3a3101f132)
while in the second:
![image](https://github.com/GoogleChromeLabs/dark-mode-toggle/assets/32283036/c7bf145c-2202-40b1-a0f4-3c57054bb459)

**Comment by tomayac** [comment]
The toggle looks perfect in both URLs, and the rule is applied properly.

<img width="434" alt="Screenshot 2023-08-23 at 00 53 38" src="https://github.com/GoogleChromeLabs/dark-mode-toggle/assets/145676/3c521a92-f113-4863-8f73-9ff8c49b078c">\


You're probably just hitting a cache issue.

**Comment by tomasts248** [comment]
Could be but when I run the website on other computers/devices I'm getting the bad one.

**Comment by tomasts248** [comment]
Even on Pagespeed it appears bad: https://pagespeed.web.dev/analysis/https-www-tomastestart-com/223ge9eejg?form_factor=mobile

Ran another and I got mixed results (bad desktop, good mobile)
https://pagespeed.web.dev/analysis/https-www-tomastestart-com/bx8bdfdktp?form_factor=desktop

Update: https://pagespeed.web.dev/analysis/https-www-tomastestart-com/9ghsgq094t?form_factor=mobile

My interpretation would be: once is fully propagated through Cloudflare those rules don't work, hence why at the beginning it loaded properly but then it eventually didn't

**Comment by tomayac** [comment]
Again, it works fine on all the devices I have tested on. Maybe test in an incognito tab? WebPageTest and the like may make themselves detectable for CDN, so maybe your CDN acts differently than it would normally when real users access the page.

**Comment by tomasts248** [comment]
Tested there and https://www.webpagetest.org/result/230823_BiDcMY_4A2/
Notice the second run contains the unwanted icon, even if in some devices it works fine and in other it doesn't is a bad user experience and unwanted, if I can get this to work reliable way I would rather not use this I'm afraid
Edit: wait I misunderstood your point, so how can I test then this for sure? and why sometimes it works properly or in other it doesn't?

> Maybe test in an incognito tab

Already done, got mixed results.

Do note I have tested with different portable browsers and different Firefox containers... And here at least I'm getting mostly bad results, problem is I understand you can't recreate it on your end :/ 
Well then I will just rollback, it has to work for every user. Thank you.

**Comment by tomayac** [comment]
Looks like you have changed the CSS. 

<img width="449" alt="Screenshot 2023-08-23 at 09 39 20" src="https://github.com/GoogleChromeLabs/dark-mode-toggle/assets/145676/a8601a38-7fba-462b-8d02-2ff828f43ba4">

Whatever you're seeing, it's not a problem with the toggle code, so I cannot really help you, sorry.

**Comment by tomasts248** [comment]
> Looks like you have changed the CSS.

I haven't and this is the proof (the loaded css):

![image](https://github.com/GoogleChromeLabs/dark-mode-toggle/assets/32283036/b8331a52-c4b6-4739-b567-4bcd0d59906d)

**Comment by tomayac** [comment]
I have successfully tried both links again now, and both work again. It really must be something your CDN is doing sometimes. Nothing more to do here. Hope you get it working.

**Comment by tomasts248** [comment]
> Hope you get it working.

Well I just ended up removing this library and implementing prefer color scheme these with vanilla JS so I'm okey, thanks.

**Comment by tomayac** [comment]
Whatever works best for you!
