### ISSUE TITLE
[feature request] support SRI (sub resources integrity)

### ISSUE THREAD

**Issue by Haocen** [GoogleChromeLabs/dark-mode-toggle#79]
Currently if CSP (content security policy) does not already include `unsafe-inline`, client browser will refuse to load inline styles from this web component.

Due to the way this project is built it is not very easy for developers to get around this limitation.

**Comment by tomayac** [comment]
There's just [one file in `dist/`](https://unpkg.com/browse/dark-mode-toggle@0.14.6/dist/dark-mode-toggle.min.mjs). Your build process would need to calculate a nonce, and then you should be good. Unless I misunderstand the problem.

**Comment by tomayac** [comment]
Following these [instructions](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#whitelisting_external_scripts_using_hashes).

**Comment by Haocen** [comment]
> There's just [one file in `dist/`](https://unpkg.com/browse/dark-mode-toggle@0.14.6/dist/dark-mode-toggle.min.mjs). Your build process would need to calculate a nonce, and then you should be good. Unless I misunderstand the problem.

No I believe styles won't be properly applied even if the script itself has SRI on it.

See https://dark-mode-toggle.pages.dev for an example.

**Comment by tomayac** [comment]
Can't you fix it based on the error message:

```bash
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-MYtDEqQW7CEY24srrOR0927vm2J5OErQMkkZQmFa0yU='), or a nonce ('nonce-...') is required to enable inline execution.
```

**Comment by Haocen** [comment]
> Can't you fix it based on the error message:
> 
> ```shell
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-MYtDEqQW7CEY24srrOR0927vm2J5OErQMkkZQmFa0yU='), or a nonce ('nonce-...') is required to enable inline execution.
> ```

It requires the hash/nonce to be added to CSP header in each response, posing a significant difficulty for those who are using static hosting services that can only change the headers configuration during deployment time.

**Comment by tomayac** [comment]
See [these tips](https://csp.withgoogle.com/docs/faq.html#static-content). It may still be a bit painful, but that's just in the matter of things.
