### ISSUE TITLE
[feature request] support Bootstrap 5.3 color modes

### ISSUE THREAD

**Issue by Haocen** [GoogleChromeLabs/dark-mode-toggle#80]
Since 5.3 Bootstrap is supporting color mode by a data attribute:
https://getbootstrap.com/docs/5.3/customize/color-modes/
It is a bit clumsy to integrate with this web component at the moment, ideally we can supply a query selector to this component to indicate the `data-bs-theme` value of the element(s) we would like to keep in sync with the toggle state, while default to the `html` tag so all elements will be included.

**Comment by tomayac** [comment]
This is already possible if you follow [this implementation guide](https://github.com/GoogleChromeLabs/dark-mode-toggle?tab=readme-ov-file#-using-a-css-class-that-you-toggle). You just need to customize the class names accordingly.

**Comment by Haocen** [comment]
> This is already possible if you follow [this implementation guide](https://github.com/GoogleChromeLabs/dark-mode-toggle?tab=readme-ov-file#-using-a-css-class-that-you-toggle). You just need to customize the class names accordingly.

Still a bit clumsy isn't it? Ideally it works out of the box, just like the css tags with `prefers-color-scheme` specified.

**Comment by tomayac** [comment]
Not everyone calls their classes the Bootstrap way… This toggle is meant to work for many use cases. If you just need one specific use case, then probably something tailor-made for Bootstrap works better.
